

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE TABLE `restaurante` (
  `id` bigint(20) NOT NULL,
  `correo_electronico` varchar(50) COLLATE utf8_spanish_ci DEFAULT NULL,
  `descripcion` varchar(600) COLLATE utf8_spanish_ci DEFAULT NULL,
  `direccion` varchar(100) COLLATE utf8_spanishhola_ci NOT NULL,
  `dirreccion_web` varchar(100) COLLATE utf8_spanish_ci DEFAULT NULL,
  `imagen` varchar(300) COLLATE utf8_spanish_ci NOT NULL,
  `informacion_adicional` varchar(600) COLLATE utf8_spanish_ci DEFAULT NULL,
  `nombre_restaurante` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  `provincia` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `publicidad_web` varchar(100) COLLATE utf8_spanish_ci DEFAULT NULL,
  `telefono` int(11) NOT NULL,
  `calificacion` int(11) NOT NULL,
  `categoria` varchar(150) COLLATE utf8_spanish_ci NOT NULL,
  `platos` varchar(500) COLLATE utf8_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;


INSERT INTO `restaurante` (`id`, `correo_electronico`, `descripcion`, `direccion`, `dirreccion_web`, `imagen`, `informacion_adicional`, `nombre_restaurante`, `provincia`, `publicidad_web`, `telefono`, `calificacion`, `categoria`, `platos`) VALUES
(1, '1@gmail.com', 'especialidad de parrilas', 'Av Melchor Urquidi 1249, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d9459577-Reviews-Las_Moras_Parrilla-Cochaba', 'https://media-cdn.tripadvisor.com/media/photo-s/09/bc/aa/e9/las-moras-parrilla.jpg', NULL, 'Las Moras Parrilla', 'cercado', NULL, 7654654, 5, 'parrilas , familiar , bar', 'parrilla de res , parrilla de pollo , almuerzo familiar'),
(2, '2@gmail.com', 'un restaurante moderno', 'Pasaje Boulevar 618 Cerca Plazuela Recoleta, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/LocationPhotoDirectLink-g297315-d1066883-i67110050-Casa_de_Campo-Coch', 'https://media-cdn.tripadvisor.com/media/photo-s/04/00/04/a2/casa-de-campo.jpg', NULL, 'Casa de Campo', 'quillacollo', NULL, 5234534, 4, 'familiar , bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos , almuerzo familiar'),
(3, '3@gmail.com', 'restaurante especializado en pastas y comida vegentaria', 'Calle Espana #409, Cochabamba 591 Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d1066898-Reviews-La_Cantonata-Cochabamba_Co', 'https://media-cdn.tripadvisor.com/media/photo-s/04/97/a2/9d/la-cantonata.jpg', NULL, 'La Cantonata', 'cercado', 'no hay', 23434523, 4, 'pastas , comida italiana , comida familiar , comida vegetariana', 'espagueti , lasaña , pitza , almuerzo familiar , tofu , ensadada sesamo'),
(4, '4@gmail.com', 'lugar de comida bufet', 'av. oquendo esquina jordad', 'https://www.consuladodebolivia.com.ar/2018/01/10/restaurantes-cochabamba-aumentan-ventas-888-gobiern', '\r\nhttps://www.consuladodebolivia.com.ar/wp-content/uploads/2018/01/fotografia_122_america-3.jpg', NULL, 'la comelona restaurant', 'cercado', NULL, 34565464, 5, 'comida bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos'),
(5, '5@gmail.com', 'un lugar agradable y comodo', 'av. german urquidi acera este 435', NULL, 'https://cdn.bolivia.com/sdi/2019/02/21/los-6-mejores-restaurantes-para-comer-en-cochabamba-712841.jpg', NULL, 'Paprika', 'cercado', NULL, 76543432, 4, 'familiar', 'chicharrones, pique, charque, laping, silpancho, majadito'),
(6, '6@gmail.com', 'un lugar de ensueños', '', NULL, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/b3/e5/dc/20170315-195852-largejpg.jpg', NULL, 'la hermosa', 'sacaba', NULL, 2345234, 2, 'comida internacional', 'comida internacional, comida italiana, comida americana, comida vegetariana'),
(7, '7@gmail.com', 'especialidad de parrilas', 'Av Melchor Urquidi 1249, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d9459577-Reviews-Las_Moras_Parrilla-Cochaba', 'https://media-cdn.tripadvisor.com/media/photo-s/09/bc/aa/e9/las-moras-parrilla.jpg', NULL, 'Las Moras Parrilla', 'cercado', NULL, 7654654, 5, 'parrilas , familiar , bar', 'parrilla de res , parrilla de pollo , almuerzo familiar'),
(8, '8@gmail.com', 'un restaurante moderno', 'Pasaje Boulevar 618 Cerca Plazuela Recoleta, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/LocationPhotoDirectLink-g297315-d1066883-i67110050-Casa_de_Campo-Coch', 'https://media-cdn.tripadvisor.com/media/photo-s/04/00/04/a2/casa-de-campo.jpg', NULL, 'Casa de Campo', 'quillacollo', NULL, 5234534, 4, 'familiar , bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos , almuerzo familiar'),
(9, '9@gmail.com', 'restaurante especializado en pastas y comida vegentaria', 'Calle Espana #409, Cochabamba 591 Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d1066898-Reviews-La_Cantonata-Cochabamba_Co', 'https://media-cdn.tripadvisor.com/media/photo-s/04/97/a2/9d/la-cantonata.jpg', NULL, 'La Cantonata', 'cercado', 'no hay', 23434523, 4, 'pastas , comida italiana , comida familiar , comida vegetariana', 'espagueti , lasaña , pitza , almuerzo familiar , tofu , ensadada sesamo'),
(10, '10@gmail.com', 'un lugar agradable y comodo', 'av. german urquidi acera este 435', NULL, 'https://cdn.bolivia.com/sdi/2019/02/21/los-6-mejores-restaurantes-para-comer-en-cochabamba-712841.jpg', NULL, 'Paprika', 'cercado', NULL, 76543432, 4, 'familiar', 'chicharrones, pique, charque, laping, silpancho, majadito'),
(11, '11@gmail.com', 'un lugar de ensueños', '', NULL, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/b3/e5/dc/20170315-195852-largejpg.jpg', NULL, 'la hermosa', 'sacaba', NULL, 2345234, 2, 'comida internacional', 'comida internacional, comida italiana, comida americana, comida vegetariana'),
(12, '12@gmail.com', 'lugar de comida bufet', 'av. oquendo esquina jordad', 'https://www.consuladodebolivia.com.ar/2018/01/10/restaurantes-cochabamba-aumentan-ventas-888-gobiern', '\r\nhttps://www.consuladodebolivia.com.ar/wp-content/uploads/2018/01/fotografia_122_america-3.jpg', NULL, 'la comelona restaurant', 'cercado', NULL, 34565464, 5, 'comida bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos'),
(13, '13@gmail.com', 'especialidad de parrilas', 'Av Melchor Urquidi 1249, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d9459577-Reviews-Las_Moras_Parrilla-Cochaba', 'https://media-cdn.tripadvisor.com/media/photo-s/09/bc/aa/e9/las-moras-parrilla.jpg', NULL, 'Las Moras Parrilla', 'cercado', NULL, 7654654, 5, 'parrilas , familiar , bar', 'parrilla de res , parrilla de pollo , almuerzo familiar'),
(14, '14@gmail.com', 'un restaurante moderno', 'Pasaje Boulevar 618 Cerca Plazuela Recoleta, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/LocationPhotoDirectLink-g297315-d1066883-i67110050-Casa_de_Campo-Coch', 'https://media-cdn.tripadvisor.com/media/photo-s/04/00/04/a2/casa-de-campo.jpg', NULL, 'Casa de Campo', 'quillacollo', NULL, 5234534, 4, 'familiar , bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos , almuerzo familiar'),
(15, '15@gmail.com', 'restaurante especializado en pastas y comida vegentaria', 'Calle Espana #409, Cochabamba 591 Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d1066898-Reviews-La_Cantonata-Cochabamba_Co', 'https://media-cdn.tripadvisor.com/media/photo-s/04/97/a2/9d/la-cantonata.jpg', NULL, 'La Cantonata', 'cercado', 'no hay', 23434523, 4, 'pastas , comida italiana , comida familiar , comida vegetariana', 'espagueti , lasaña , pitza , almuerzo familiar , tofu , ensadada sesamo'),
(16, '16@gmail.com', 'lugar de comida bufet', 'av. oquendo esquina jordad', 'https://www.consuladodebolivia.com.ar/2018/01/10/restaurantes-cochabamba-aumentan-ventas-888-gobiern', '\r\nhttps://www.consuladodebolivia.com.ar/wp-content/uploads/2018/01/fotografia_122_america-3.jpg', NULL, 'la comelona restaurant', 'cercado', NULL, 34565464, 5, 'comida bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos'),
(17, '17@gmail.com', 'un lugar agradable y comodo', 'av. german urquidi acera este 435', NULL, 'https://cdn.bolivia.com/sdi/2019/02/21/los-6-mejores-restaurantes-para-comer-en-cochabamba-712841.jpg', NULL, 'Paprika', 'cercado', NULL, 76543432, 4, 'familiar', 'chicharrones, pique, charque, laping, silpancho, majadito'),
(18, '18@gmail.com', 'un lugar de ensueños', '', NULL, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/b3/e5/dc/20170315-195852-largejpg.jpg', NULL, 'la hermosa', 'sacaba', NULL, 2345234, 2, 'comida internacional', 'comida internacional, comida italiana, comida americana, comida vegetariana'),
(19, '19@gmail.com', 'especialidad de parrilas', 'Av Melchor Urquidi 1249, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d9459577-Reviews-Las_Moras_Parrilla-Cochaba', 'https://media-cdn.tripadvisor.com/media/photo-s/09/bc/aa/e9/las-moras-parrilla.jpg', NULL, 'Las Moras Parrilla', 'cercado', NULL, 7654654, 5, 'parrilas , familiar , bar', 'parrilla de res , parrilla de pollo , almuerzo familiar'),
(20, '20@gmail.com', 'un restaurante moderno', 'Pasaje Boulevar 618 Cerca Plazuela Recoleta, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/LocationPhotoDirectLink-g297315-d1066883-i67110050-Casa_de_Campo-Coch', 'https://media-cdn.tripadvisor.com/media/photo-s/04/00/04/a2/casa-de-campo.jpg', NULL, 'Casa de Campo', 'quillacollo', NULL, 5234534, 4, 'familiar , bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos , almuerzo familiar'),
(21, '21@gmail.com', 'restaurante especializado en pastas y comida vegentaria', 'Calle Espana #409, Cochabamba 591 Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d1066898-Reviews-La_Cantonata-Cochabamba_Co', 'https://media-cdn.tripadvisor.com/media/photo-s/04/97/a2/9d/la-cantonata.jpg', NULL, 'La Cantonata', 'cercado', 'no hay', 23434523, 4, 'pastas , comida italiana , comida familiar , comida vegetariana', 'espagueti , lasaña , pitza , almuerzo familiar , tofu , ensadada sesamo'),
(22, '22@gmail.com', 'un lugar agradable y comodo', 'av. german urquidi acera este 435', NULL, 'https://cdn.bolivia.com/sdi/2019/02/21/los-6-mejores-restaurantes-para-comer-en-cochabamba-712841.jpg', NULL, 'Paprika', 'cercado', NULL, 76543432, 4, 'familiar', 'chicharrones, pique, charque, laping, silpancho, majadito'),
(23, '23@gmail.com', 'lugar de comida bufet', 'av. oquendo esquina jordad', 'https://www.consuladodebolivia.com.ar/2018/01/10/restaurantes-cochabamba-aumentan-ventas-888-gobiern', '\r\nhttps://www.consuladodebolivia.com.ar/wp-content/uploads/2018/01/fotografia_122_america-3.jpg', NULL, 'la comelona restaurant', 'cercado', NULL, 34565464, 5, 'comida bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos'),
(24, '24@gmail.com', 'un lugar de ensueños', '', NULL, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/b3/e5/dc/20170315-195852-largejpg.jpg', NULL, 'la hermosa', 'sacaba', NULL, 2345234, 2, 'comida internacional', 'comida internacional, comida italiana, comida americana, comida vegetariana'),
(25, '25@gmail.com', 'especialidad de parrilas', 'Av Melchor Urquidi 1249, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d9459577-Reviews-Las_Moras_Parrilla-Cochaba', 'https://media-cdn.tripadvisor.com/media/photo-s/09/bc/aa/e9/las-moras-parrilla.jpg', NULL, 'Las Moras Parrilla', 'cercado', NULL, 7654654, 5, 'parrilas , familiar , bar', 'parrilla de res , parrilla de pollo , almuerzo familiar'),
(26, '26@gmail.com', 'un restaurante moderno', 'Pasaje Boulevar 618 Cerca Plazuela Recoleta, Cochabamba Bolivia', 'https://www.tripadvisor.com.pe/LocationPhotoDirectLink-g297315-d1066883-i67110050-Casa_de_Campo-Coch', 'https://media-cdn.tripadvisor.com/media/photo-s/04/00/04/a2/casa-de-campo.jpg', NULL, 'Casa de Campo', 'quillacollo', NULL, 5234534, 4, 'familiar , bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos , almuerzo familiar'),
(27, '27@gmail.com', 'restaurante especializado en pastas y comida vegentaria', 'Calle Espana #409, Cochabamba 591 Bolivia', 'https://www.tripadvisor.com.pe/Restaurant_Review-g297315-d1066898-Reviews-La_Cantonata-Cochabamba_Co', 'https://media-cdn.tripadvisor.com/media/photo-s/04/97/a2/9d/la-cantonata.jpg', NULL, 'La Cantonata', 'cercado', 'no hay', 23434523, 4, 'pastas , comida italiana , comida familiar , comida vegetariana', 'espagueti , lasaña , pitza , almuerzo familiar , tofu , ensadada sesamo'),
(28, '28@gmail.com', 'lugar de comida bufet', 'av. oquendo esquina jordad', 'https://www.consuladodebolivia.com.ar/2018/01/10/restaurantes-cochabamba-aumentan-ventas-888-gobiern', '\r\nhttps://www.consuladodebolivia.com.ar/wp-content/uploads/2018/01/fotografia_122_america-3.jpg', NULL, 'la comelona restaurant', 'cercado', NULL, 34565464, 5, 'comida bufet', 'bufet de ensaladas , bufet de carnes , bufet de complementos'),
(29, '29@gmail.com', 'un lugar agradable y comodo', 'av. german urquidi acera este 435', NULL, 'https://cdn.bolivia.com/sdi/2019/02/21/los-6-mejores-restaurantes-para-comer-en-cochabamba-712841.jpg', NULL, 'Paprika', 'cercado', NULL, 76543432, 4, 'familiar', 'chicharrones, pique, charque, laping, silpancho, majadito'),
(30, '30@gmail.com', 'un lugar de ensueños', '', NULL, 'https://media-cdn.tripadvisor.com/media/photo-s/0e/b3/e5/dc/20170315-195852-largejpg.jpg', NULL, 'la hermosa', 'sacaba', NULL, 2345234, 2, 'comida internacional', 'comida internacional, comida italiana, comida americana, comida vegetariana');


ALTER TABLE `restaurante`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `restaurante`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;
COMMIT;
